# Generated by Django 3.1.7 on 2021-03-23 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_auto_20210323_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postrate',
            old_name='liked',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='postrate',
            old_name='rated_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postrate',
            old_name='rated_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='evaluator',
            field=models.ManyToManyField(related_name='post_rated', through='content.PostRate', to=settings.AUTH_USER_MODEL),
        ),
    ]
